baseURL = 'http://localhost:1313'
languageCode = "en-us"
title = "Heron lake"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

[params]
	mode = "toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
    subtitle  = "Applying math to solve different problems."
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/wesenheit"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
